### ISSUE TITLE
[Arabic] Dancing Dots dialogs do not work

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#100]
Even if the IDs seems to be set correctly in **Arabic_MiniGame_ProFuturo**, the audios are not played.
![image](https://user-images.githubusercontent.com/17926293/103243020-b2c2e980-4958-11eb-9f3b-e0f3e6d8dc73.png)

The Title is set to `DancingDots_letterany_Title` but the debug log returns the following warning when the dialog should be played in the Game Launcher:
`Keeper trying to play audio for PlayDialogue: Game_DancingDots_letterany_Title`
`Cannot find id 'Game_DancingDots_letterany_Title' in table LocalizationTable`

And once in the game itself, no audio is played even if the log suggest the correct resources should be played:
`Keeper trying to play audio for PlayDialogue: DancingDots_letterany_Intro`
`Keeper trying to play audio for PlayDialogue: DancingDots_letterany_Tuto`

**Comment by FrancyCavallari** [comment]
The exact same problem is problem is present also in MakeFriends and  Maze...
... all games that were not present in the Learn English version.
So I suspect that either the games have not been updated to manage the IDs correctly or the Game Launcher was not updated to handle those games correctly.

**Comment by CatmanIta** [comment]
Found the problem: the ID in "Title Id" you see is the LocalizationData ID, not the audio ID.
The LocalizationData ID holds the Audio ID, which for DancingDots (and other games) has "Game_" put before it, which is wrong.

![image](https://user-images.githubusercontent.com/3244662/104715814-52d58c80-5727-11eb-8690-4765f726462a.png)

Removing the "Game_" from the localization table fixed the problem.

Also, the same must be done for Intro and Tuto instances.
