### ISSUE TITLE
[Arabic] End Scene is missing the text/dialog to read

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#101]
In the original Arabic game the End scene told the player he/she can now read and a text message (End_Scene_2 = "You are awesome!") was displayed but it was not played...  
... but this step was removed in the Learn English version since it was not meaningful anymore.

How should we manage this situation?
Maybe we can skip the written-only dialog and force the subtitle to be ON in the Ending Scene... since we have a played dialog (I think it's End_Scene_1_2)  suggesting that the player can now read.

**Comment by CatmanIta** [comment]
We force subtitles to ON for that scene, and from then on.

**Comment by CatmanIta** [comment]
Do that only if subtitles can be used, however.

**Comment by FrancyCavallari** [comment]
Waiting Arabic_legacy texts to be fixed ( #110 ) in order to verify this issue
