### ISSUE TITLE
[Arabic] the Book should support RTL layout for RTL languages... 

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#105]
... while keeping the current LTR layout for LTR languages

**Comment by StefanoCecere** [comment]
words to align automatically to right, now

**Comment by StefanoCecere** [comment]
@CatmanIta we need to reverse the order of these 3 columns by RTL config.
i couldn't do it by Horizontal layout.

<img width="359" alt="Screenshot 2021-02-10 at 13 27 44" src="https://user-images.githubusercontent.com/640536/107510174-dd34d300-6ba3-11eb-8605-99d8e992fc55.png">

**Comment by CatmanIta** [comment]
Done
