### ISSUE TITLE
[Arabic] Reserved Area should be fixed (and improved?) 

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#114]
Bugs:
- it seems that the small font includes Arabic numbers making it impossible to read the version number and the Profile ID
- the Profile ID is RTL instead of LTR (it should be LTR because it should use Latin font and numbers)
- DONATE appears in English

![image](https://user-images.githubusercontent.com/17926293/105854595-5dc1d400-5fe7-11eb-8995-8ea0e850f9c2.png)

PS: 
- do we want to have the labels in Arabic+English (Learning+Help language)?
- do we want to rework the layout (i.e. re-adding some button that were present in the original version)?
- the Review feature is quite useless at the moment, can we make it more useful?

**Comment by wassimbassil** [comment]
Works fine on android
