### ISSUE TITLE
[Arabic] Gender selection: Non readable text

### ISSUE THREAD

**Issue by wassimbassil** [vgwb/Antura#119]
- In the gender selection option, the Arabic words are reversed and not attached (only the big text, the yellow bar is correct)

It should read (right to left)
يتم طلب الجنس فقط من أجل مخاطبة اللاعبين باستخدام النموذج الصحيح (ذكر أو أنثى). لا يتم جمع هذه المعلومات أو استخدامها بأي طريقة 
                                                                                                                                                                                                    أخرى

![NonReadableText_Gender](https://user-images.githubusercontent.com/61846526/106463099-3fe8e900-6497-11eb-9de9-16118b3f1ffd.jpg)

**Comment by CatmanIta** [comment]
Fixed the orientation issue, but I'm not really sure about the text content. @FrancyCavallari let's talk about this

**Comment by FrancyCavallari** [comment]
It seems ok to me... @wassimbassil can you please pull from Git and check that the text is ok now?

**Comment by wassimbassil** [comment]
yes it is readable now.
