### ISSUE TITLE
[Arabic] In the teacher's Book, the spelling of Words is reversed

### ISSUE THREAD

**Issue by wassimbassil** [vgwb/Antura#120]
In the Teacher's Book, in the Words section, the spelling of all the words is reversed (should start from right to left)

![20210201_141913](https://user-images.githubusercontent.com/61846526/106464285-bcc89280-6498-11eb-8ab5-bd9fc0697972.jpg)
)

**Comment by FrancyCavallari** [comment]
Linked with #105

**Comment by wassimbassil** [comment]
yes, it is OK now.
