### ISSUE TITLE
[Arabic] Lyrics of the alphabet song  is reversed and not attached.

### ISSUE THREAD

**Issue by wassimbassil** [vgwb/Antura#122]
- In the the alphabet song, only the text is reversed and the letters are not attached.

It should be: 
من الألف إلى الياء
هذه لغتي يا أحبّاء
من الألف إلى الياء
هيّا نلعب يا أحبّاء

![Non ReadbleText_AlphabetSong](https://user-images.githubusercontent.com/61846526/106463096-3eb7bc00-6497-11eb-972b-a62adb7eb33e.jpg)

**Comment by FrancyCavallari** [comment]
The text was correct in the Gplay version, so we must have introduced the bug with the new system
