### ISSUE TITLE
[Arabic] Teacher's Area unlock instruction: colors are reversed in arabic.

### ISSUE THREAD

**Issue by wassimbassil** [vgwb/Antura#123]
In the Arabic phrase, the color that should be pressed 5 times is switched with the color that should be pressed 1 time.

for example, in the pic below, the Arabic phrase says: press the GREEN button 5 times then the RED button once.

![20210203_101928](https://user-images.githubusercontent.com/61846526/106727479-d1796780-660b-11eb-8dcb-001f2561e82e.jpg)

**Comment by CatmanIta** [comment]
The text must be changed by switching the {1} and {2} @FrancyCavallari 

![image](https://user-images.githubusercontent.com/3244662/106729647-04bcf600-660e-11eb-8929-c127bc2e8481.png)

**Comment by FrancyCavallari** [comment]
I fixed the text in the Google Sheet... but we still have to re-import it
