### ISSUE TITLE
[Arabic] MakeFriends_LetterInWord: sometimes the correct answer is not available.

### ISSUE THREAD

**Issue by wassimbassil** [vgwb/Antura#124]
In the friendship game, sometimes, the correct answer is not available to choose and have to choose an incorrect letter to move on.

PS: the audio of the incorrect letter sounds like the correct letter.

![Game_Friendship_01](https://user-images.githubusercontent.com/61846526/106735591-be1eca00-6614-11eb-99f5-fda633c7c6b1.jpg)

![Game_Friendship_02](https://user-images.githubusercontent.com/61846526/106735592-beb76080-6614-11eb-8358-7de7108f9e5d.jpg)

**Comment by CatmanIta** [comment]
![image](https://user-images.githubusercontent.com/3244662/107487812-de0b3c00-6b86-11eb-8317-638132ce0451.png)
![image](https://user-images.githubusercontent.com/3244662/107487827-e2cff000-6b86-11eb-90a0-a090617919c9.png)

The arabic splitter does not treat medial forms correctly, it seems. I am investigating (images are for reference as an example of  error)

**Comment by CatmanIta** [comment]
Showing choice: LL-(سً) F-Medial seen_fathah with text ـﺴَ

In this case, the letter shown below should be the medial form, but this does not seem like it
