### ISSUE TITLE
[Arabic] Friendship Game: sometimes, the images of the words don't turn when pressed.

### ISSUE THREAD

**Issue by wassimbassil** [vgwb/Antura#125]
Sometimes, the images of the words don't turn when pressed, only the audio is played.

https://user-images.githubusercontent.com/61846526/106735944-1fdf3400-6615-11eb-9c7a-d54ccaadb8d7.mp4

**Comment by CatmanIta** [comment]
This is due to how difficulty is setup.
We decided to change it as such:
- EASY remains as is
- NORMAL hides words, but you can click to make them turn and they remain for a time
- HARD is like normal, but with less time
