### ISSUE TITLE
[Arabic] Catapult Game - Spelling mini game: photo and word mismatch

### ISSUE THREAD

**Issue by wassimbassil** [vgwb/Antura#127]
When I get an incorrect answer and lose all hearts, the word I was supposed to spell is stuck even though the images and words change, and even if I get the answer right after.

If I make a mistake again and lose all hearts, the same thing happens with that second word I was supposed to spell: it gets stuck until I lose all hearts again.

If I don't lose all hearts from the start, the game continues normally.

![Game_Catapult_Spelling_01](https://user-images.githubusercontent.com/61846526/106742633-908a4e80-661d-11eb-99ff-6f2933c5e34a.jpg)

![Game_Catapult_Spelling_02](https://user-images.githubusercontent.com/61846526/106742635-91bb7b80-661d-11eb-9113-5a74560cbb01.jpg)

**Comment by CatmanIta** [comment]
This was due to a coroutine not being stopped correctly in the game.
