### ISSUE TITLE
[Arabic] MakeFriends_LetterInWord:  The audio does not match the letter.

### ISSUE THREAD

**Issue by wassimbassil** [vgwb/Antura#130]
As shown in the console, some letters are pronounced as different letters.

![Game_Makefriends_WrongAudio_01](https://user-images.githubusercontent.com/61846526/107349239-447d5500-6ac8-11eb-8b93-9d474d1d404f.jpg)

**Comment by wassimbassil** [comment]
It seems fine now except one letter as per the image below

![Game_Makefriends_WrongAudio_02](https://user-images.githubusercontent.com/61846526/107503440-40216c80-6b9a-11eb-90b9-1ab962dc6dc9.jpg)

**Comment by FrancyCavallari** [comment]
We have already it sound from alef_fathah to teh_sukun... so it will be fixed as soon as we re-import the vocabulary
