### ISSUE TITLE
[Arabic] MakeFriends_LetterInWord: Sometimes the common letter does not light up.

### ISSUE THREAD

**Issue by wassimbassil** [vgwb/Antura#132]
![Game_Makefriends_NoHighlight_01](https://user-images.githubusercontent.com/61846526/107354636-b062bc00-6ace-11eb-997e-d0fd216aec1d.jpg)

**Comment by FrancyCavallari** [comment]
This bug has been known for a long time but we have never been able to find a repro rule to help understand why it happens :-(

**Comment by wassimbassil** [comment]
I noticed that it mostly happens when the answer is either in:
- incorrect form 
- or wrong letter but with correct audio

**Comment by FrancyCavallari** [comment]
Thanks @wassimbassil , anyway, better we fix the rest of the bugs on Make Friends before investigating this one deeper...

**Comment by CatmanIta** [comment]
Yes, I noticed it happening too while trying to fix the other bug. I think it is related. Thank you for added the information

**Comment by CatmanIta** [comment]
This seems to happen when the isolated and final forms are the same, such as in this case
![image](https://user-images.githubusercontent.com/3244662/107486092-e5314a80-6b84-11eb-9a52-415c8b11b87a.png)

It's the same bug as the other cases, so it should disappear as I fix that
