### ISSUE TITLE
[Arabic] MissingLetter_LetterInWord: sometimes it is the wrong form of the correct letter

### ISSUE THREAD

**Issue by wassimbassil** [vgwb/Antura#133]
![Game_MissingLetters_WrongLetters_01](https://user-images.githubusercontent.com/61846526/107355827-4e0abb00-6ad0-11eb-970f-4714b81b01de.jpg)
![Game_MissingLetters_WrongLetters_02](https://user-images.githubusercontent.com/61846526/107355828-4ea35180-6ad0-11eb-9a2f-7dbd99086f50.jpg)
![Game_MissingLetters_WrongLetters_03](https://user-images.githubusercontent.com/61846526/107355829-4ea35180-6ad0-11eb-9e42-c87be4d130e0.jpg)

**Comment by wassimbassil** [comment]
the bug is still there

**Comment by FrancyCavallari** [comment]
The correct answer always appears in the Isolated form
