### ISSUE TITLE
[Arabic] Game Assessment_MatchLettersToWord_Form: No intro dialogue or Subtitles.

### ISSUE THREAD

**Issue by wassimbassil** [vgwb/Antura#134]

**Comment by CatmanIta** [comment]
The problem is that there is no "Assessment_Match_Letters_Words" in the Dialogs folder. It is in "Dialogs_ea4s", which is not used!

I added an error if an audio file is not found so we can catch these.

**Comment by FrancyCavallari** [comment]
I also noticed that the IntroID in the minigame DB are empty for all assessments... I'm fixing it.

**Comment by FrancyCavallari** [comment]
It seems that the Intro ID is not really used (the dialogs must be hardcoded in the assessment code) ...
... and I also found few other audio files missing.
Anyway now it's fixed.
