### ISSUE TITLE
[Arabic] MakeFriends: we could highlight the correct letter in the Ui and in both words during the turorial round

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#136]
We could use the same blinking-green effect used in ThrowBalls_BuildWord

**Comment by CatmanIta** [comment]
Al momento la situazione è:
il flashing è specifico per quel gioco e solo per quell'elemento grafico, e gestito da una coroutine gesttita dal learning helper.
Invece la cosa corretta sarebbe:
spostare il flashing in una coroutine generica che funzioni per qualsiasi TextRender
spostare la logica che highlighta una lettera sola in un punto comune ai giochi
