### ISSUE TITLE
[Arabic] In Game Assessment_MatchLettersToWord_Form the missing letter now appears a BLACK BOX instead of an empty box

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#139]
![image](https://user-images.githubusercontent.com/17926293/107652055-7802df80-6c80-11eb-824f-a250363d3fcd.png)

Most likely it's a side effect of updating TMPro because few days ago it was ok... check #129

**Comment by CatmanIta** [comment]
This is actually Assessment_CompleteWord_Form

**Comment by wassimbassil** [comment]
Issue resolved
