### ISSUE TITLE
[Arabic] Word Categories in the Book are the LearnEnglish ones... 

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#141]
.. so many words do not appear in the Book and the Math category is empty.
![image](https://user-images.githubusercontent.com/17926293/108181525-54b8b400-7108-11eb-9234-8cd83b95dab3.png)

Where is defined the list of categories?
I suppose we should allow the list of categories to change for each edition...

**Comment by FrancyCavallari** [comment]
We must define a standard list of categories for all Editions and all words must be assigned to a category (otherwise they won't appear in the book)

**Comment by StefanoCecere** [comment]
now the categories list is:
```
    public enum WordDataCategory
    {
        None = 0,
        Animals = 1,
        Body = 2,
        City = 3,
        Clothes = 4,
        Colors = 5,
        Days = 6,
        Family = 7,
        Food = 8,
        Home = 9,
        Months = 10,
        Nature = 11,
        Numbers = 12,
        Objects = 13,
        Seasons = 14,
        Expressions = 15,
        Feelings = 16,
        Jobs = 17,
        NumbersOrdinal = 18,
        Math = 19
    }
```
