### ISSUE TITLE
[Arabic] Song_Alphabet game: Ending subtitles pop up in middle of song (no audio)

### ISSUE THREAD

**Issue by wassimbassil** [vgwb/Antura#145]

**Comment by FrancyCavallari** [comment]
Subtitles appear both halfway in the song (briefly) and at the end.. but no voice dialog is heard

**Comment by CatmanIta** [comment]
It seems it was done on purpose.
 We have the `Song_alphabet_SingWithMe `dialoge played, but only as subtitles. What would you like to have instead?

**Comment by wassimbassil** [comment]
The subtitles of the 'Song_alphabet_SingWithMe' dialogue should only appear at the end of the song. 

In addition when it does appear at the end of the song, there is no corresponding audio.


https://user-images.githubusercontent.com/61846526/110619834-933a0f80-8198-11eb-982c-75bdfe8ac4dc.mp4
