### ISSUE TITLE
[Arabic] In the Book, for dubug only, add the combinations with Shaddah for each letter

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#149]

**Comment by StefanoCecere** [comment]
we added a check box to the book component

**Comment by StefanoCecere** [comment]
when playing the Book scene, check the "Debug/Test Shaddah" checkbox in the Book(Clone) gameobject

<img width="638" alt="Screenshot 2021-07-21 at 06 18 51" src="https://user-images.githubusercontent.com/640536/126430366-824bcee5-5545-4be5-b487-b48c00bb106f.png">
