### ISSUE TITLE
[Arabic Addressable] Adjust Position of diacritics in Book

### ISSUE THREAD

**Issue by wassimbassil** [vgwb/Antura#158]
![basketaball](https://user-images.githubusercontent.com/61846526/119221576-553e5d80-baf0-11eb-9deb-9c099d5025c6.jpg)
![Number06](https://user-images.githubusercontent.com/61846526/119221577-55d6f400-baf0-11eb-80f8-e195ddd3ed55.jpg)
![Number07](https://user-images.githubusercontent.com/61846526/119221578-566f8a80-baf0-11eb-8f61-7ffb11a3da25.jpg)
![teacher](https://user-images.githubusercontent.com/61846526/119221579-566f8a80-baf0-11eb-8cbc-40937ca70bbe.jpg)
![the_meeting](https://user-images.githubusercontent.com/61846526/119221581-566f8a80-baf0-11eb-8441-f0ed89dec690.jpg)
![TheBear](https://user-images.githubusercontent.com/61846526/119221582-57082100-baf0-11eb-89ec-ee839ee15a51.jpg)
![theshop](https://user-images.githubusercontent.com/61846526/119221585-57082100-baf0-11eb-81b2-7eea7b2524e0.jpg)
![washingmachine](https://user-images.githubusercontent.com/61846526/119221586-57a0b780-baf0-11eb-9d77-614a186972ba.jpg)

**Comment by FrancyCavallari** [comment]
In the Android build 189 all words/diacritics appear exactly as in the above screenshot... so nothing has changed/fixed
