### ISSUE TITLE
[Arabic Addressable] Teachers Area: in the instructions text, the second color is missing in english and arabic

### ISSUE THREAD

**Issue by wassimbassil** [vgwb/Antura#161]
![teachers_area](https://user-images.githubusercontent.com/61846526/119221932-17423900-baf2-11eb-9cc6-7c7b31a17c34.jpg)

**Comment by FrancyCavallari** [comment]
I suspect that something is wrong with the DBs... maybe we have to re-imprt everything after switching to the Addressable (even if I don't see why)?

**Comment by FrancyCavallari** [comment]
In English the word "Jobs"  is used instead of "green".
In Arabic the word is missing

**Comment by FrancyCavallari** [comment]
Tested on Android Addressable v6 and it's still present

**Comment by CatmanIta** [comment]
I just tested it before pulling the merge and the problem is not there, so it's not due to addressable switch.
It's probably due to the updated DB.
 I'm updating now to check what went wrong

**Comment by CatmanIta** [comment]
It still won't give me an error, so I don't think it's due to the DB, so maybe it's something with how it builds android data bundles? I'm checking with the build

**Comment by CatmanIta** [comment]
It's the LocalizationID, it's not updated

**Comment by wassimbassil** [comment]
Just tested it and the issue is still there

**Comment by FrancyCavallari** [comment]
Everything should be ok now
![image](https://user-images.githubusercontent.com/17926293/123075814-d7d07a80-d418-11eb-87f1-f6013e267287.png)
