### ISSUE TITLE
[Arabic} Book: Missing audio for 'cold_adjective' and 'the_well-being'

### ISSUE THREAD

**Issue by wassimbassil** [vgwb/Antura#175]

**Comment by CatmanIta** [comment]
"cold_adjective": the audio file is indeed missing, do you have it somewhere?
"the_well-being": the audio file had the wrong name, fixed

**Comment by FrancyCavallari** [comment]
@StefanoCecere please check if we have "cold_adjective" audio file in the old projects

**Comment by StefanoCecere** [comment]
we don't have cold_adjective audio

**Comment by wassimbassil** [comment]
"cold_adjective": correct audio
"the_well-being": still missing audio
