### ISSUE TITLE
[Arabic] MiniGame MIxedLetters: sometimes the Forms of letters are not correct (It is most recurrent with the letters bah - tah - thah -noon)

### ISSUE THREAD

**Issue by wassimbassil** [vgwb/Antura#176]
![MixedLetters_Buildword_TaMiddle](https://user-images.githubusercontent.com/61846526/139717876-84e9a4f3-b44d-442c-8e94-9ff8a5c6021f.jpg)
![MixedLetters_Buildword_TaFinal](https://user-images.githubusercontent.com/61846526/139717894-9b4e2768-543e-433b-bc0a-6f710089c80c.jpg)

**Comment by CatmanIta** [comment]
The issue was that there was a bug that showed only the isolated letters
