### ISSUE TITLE
[Arabic] [Book] "tah" letter does not manage well shaddah on 2 of its forms

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#178]
It may be the same problem we found happening when the order of shaddah-diacritic is reverted
![image](https://user-images.githubusercontent.com/17926293/140169205-a7e6a39b-196c-4001-b3bd-ef0415de372e.png)

**Comment by FrancyCavallari** [comment]
The same happens with the letter "zah"
![image](https://user-images.githubusercontent.com/17926293/140170025-e1cdd3b1-f70f-4bba-a92f-5f83eac82aba.png)

**Comment by CatmanIta** [comment]
Fixed
