### ISSUE TITLE
[Arabic] A few letters cannot be edited with the DiacriticsCombo Editor

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#180]
Hamza (with all diacritics)
![image](https://user-images.githubusercontent.com/17926293/140406517-c71a622e-db78-4518-af7e-106fdde92645.png)

Lam_alef_hamza_hi
![image](https://user-images.githubusercontent.com/17926293/140406779-c0eb8e17-6f6f-4cf9-9e52-afb29953aec1.png)

There are more special letters (LetterVariations) not appearing in the editor but these 2 seems to be the only one we need to fix problems.

**Comment by wassimbassil** [comment]
I will also add the position of the kasrah itself is a bit too high in comparison with the other diacritics

![Screenshot_20211108-174303_Antura Arabic](https://user-images.githubusercontent.com/61846526/141020217-d1d4e2fd-8f56-444f-99ef-b5d5689aebcb.jpg)

**Comment by CatmanIta** [comment]
We decided to add all letters from the DB to the diacritic combo editor, so to make sure we can have all combos.
We also decided to create a diacritic combo table for each language.
