### ISSUE TITLE
[Arabi] Missing Shaddah in letters that are the correct answer but should have a Shaddah

### ISSUE THREAD

**Issue by wassimbassil** [vgwb/Antura#181]
In all the minigames where we have to solve a WORD... when the word has a letter with shaddah, and that letter is the answer that the player has to choose, the shaddah would be missing from the letter and word. The correct word with shaddah only appears when the word is introduced and after it is solved.

![Screenshot_20211109-231941_Antura Arabic](https://user-images.githubusercontent.com/61846526/141021704-e17c4df5-8015-411d-9cdc-03474faa631a.jpg)
![Screenshot_20211109-232613_Antura Arabic](https://user-images.githubusercontent.com/61846526/141021713-0b712dfa-3fff-4ffd-a60d-012eaae83fde.jpg)
![Screenshot_20211109-230422_Antura Arabic](https://user-images.githubusercontent.com/61846526/141021785-a454c842-4159-4e54-8d84-44d1043057e1.jpg)
![Screenshot_20211109-230515_Antura Arabic](https://user-images.githubusercontent.com/61846526/141021791-a50493b3-b6e1-4e9f-aa1b-9ef008b9d61f.jpg)

**Comment by FrancyCavallari** [comment]
Bu design the Shaddah is only shown over full words... never on a single letter!
