### ISSUE TITLE
[Arabic]  In the MiniGame titles, the alef_maqsura looks disconnected from the word when it should be in it's final form.

### ISSUE THREAD

**Issue by wassimbassil** [vgwb/Antura#183]
![Screenshot_20211108-182042_Antura Arabic](https://user-images.githubusercontent.com/61846526/141023090-2fa267e7-a3af-4256-88a3-d0833b57f86c.jpg)
![Screenshot_20211109-231317_Antura Arabic](https://user-images.githubusercontent.com/61846526/141023094-be022578-bf1d-4442-a2f2-39e28af76e7b.jpg)

**Comment by CatmanIta** [comment]
That phrase was using the FARSI YEH letter instead of the ALEF MAQSURA letter.
We will transform any FARSI YEH we find to the correct letter now.
