### ISSUE TITLE
[Afgha] Multi-edition selector

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#185]
Design and implement the multi-edition selector.
Can we have 6 profiles for any edition?

**Comment by CatmanIta** [comment]
Yes, we can separate the profiles

**Comment by CatmanIta** [comment]
Layout will be: image + text OR text only, on a grid. Then you press play to advance.

**Comment by CatmanIta** [comment]
We decided with Stefano to separate what is the App config from the Edition config. 
The App will be the one that references the 'build', while each Edition will be what is now the child editions, i.e. has data about the journey, DB, and languages.

Here is an example:
![image](https://user-images.githubusercontent.com/3244662/142182842-4947932c-8cde-4a23-91cc-931aa4cc80a0.png)

@FrancyCavallari

**Comment by CatmanIta** [comment]
We changed it to AppEdition & LanguageEdition

**Comment by CatmanIta** [comment]
Also, the selector should spell out with audio what the selections are

**Comment by CatmanIta** [comment]
Added logic and flow.
Multi-edition now works correctly.
Profiles are now handled separately per lang edition.

What is missing:
rename LangConfig to ContentConfig
save the ContentEdition enum instead of the current lang index

**Comment by FrancyCavallari** [comment]
We still need design, produce and integrate the proper UI for the Edition Selector

**Comment by FrancyCavallari** [comment]
Here we have the name of the languages in the same language:
Dari : دری
Pashtu: پښتو

We checked and there's no meaningful way to associate an image/flag to each language... so we thought about using the "Antura and the Letters" logo localized in each language.

**Comment by FrancyCavallari** [comment]
Layout poposal: 
![image](https://user-images.githubusercontent.com/17926293/146778222-c3b6ef8f-74e5-47c1-9d0c-1e236c18f311.png)

**Comment by CatmanIta** [comment]
Here is how it appears with the current UI

![image](https://user-images.githubusercontent.com/3244662/147937506-338c66c4-ecf6-4ec6-a2b2-1ab009f792b5.png)

**Comment by CatmanIta** [comment]
![image](https://user-images.githubusercontent.com/3244662/147937873-d9cb160a-f76d-4b50-938a-27a89c0b8a7c.png)

**Comment by FrancyCavallari** [comment]
In the homepage the Edition button is wrongly positioned in the bottom-right corner:
![Uploading image.png…]()

And we still have to define how this button should look like... maybe the easiest solution is to simply write Dari or Pastho into an orange rectangle: 
Dari : دری
Pashto: پښتو

**Comment by FrancyCavallari** [comment]
PS: the letter "shin" appear in the final form here instead of medial form
![image](https://user-images.githubusercontent.com/17926293/148957840-d59ee277-9c5d-4859-94aa-25d0856ac13d.png)

**Comment by CatmanIta** [comment]
We will use a Speech Bubble (like that in MakeFriends) with the name inside

**Comment by CatmanIta** [comment]
Added. The issue with the wrong letter is related to Pahsto not having unicodes at all.
We need to find a way to fix that.

**Comment by FrancyCavallari** [comment]
Edition selector popup background does not work correctly on 4:3 (iPad) aspect ratio
![image](https://user-images.githubusercontent.com/17926293/149225410-0015e36a-1fee-4d8d-a517-826aacfad10e.png)

**Comment by FrancyCavallari** [comment]
I noticed a couple of additional issues linked with the Edition Selector:
1. first fo all the temp logo appearing in the main meno (the arabic one) does not appear in the selector (white rectangle instead)
2. after the first launch, the selector should not appear anymore (except if the player presses the edition button)... but if you press (+) to create a new profile and then abort it (pause + quit) you get the Edition Selector again!

**Comment by FrancyCavallari** [comment]
About the previous comment, I noticed that there was no image assigned to the "Icon" field in the Content Edition... once set both issues listed above seems to be solved
