### ISSUE TITLE
[DB] Leave the PS DB on GDrive or create a custom editor in Unity?  

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#187]
We could also implement the automatic Word filtering according to "tags" (i.e. Category) during PS import/update

**Comment by CatmanIta** [comment]
Tags are paramount.
Optionally, we could have some validation on the data in GDrive too.

**Comment by CatmanIta** [comment]
You will find a "PlaySessionLink" in all vocabulary data now. Test it out!

It's optional, so single vocabulary elements are still supported (and not having a PlaySessionLink column won't break editions)
