### ISSUE TITLE
[Analytics] Update to the new Unity Analytics

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#191]

**Comment by CatmanIta** [comment]
![image](https://user-images.githubusercontent.com/3244662/143200732-c4c4393e-7bf5-4a5a-8b94-ddf27ec8d3bf.png)
It seems we are already on the latest version.

**Comment by StefanoCecere** [comment]
manual: https://docs.unity.com/analytics/RecordingCustomEvents.htm

**Comment by CatmanIta** [comment]
Note: we'll add the Init for now so we can see if the standard events work

**Comment by CatmanIta** [comment]
They seem to work, I'm marking this to validate

**Comment by FrancyCavallari** [comment]
@StefanoCecere let's check if everything was done and working
