### ISSUE TITLE
When you reach exactly 0 cookies purchasing an item after having bought a photo, you cannot buy

### ISSUE THREAD

**Issue by CatmanIta** [vgwb/Antura#195]
ci è arrivata una mail in Arabo per un problema con lo shop dell'Antura Space... Wassim sta indagando ma sembra che "the problem only happens when you reach exactly 0 cookies purchasing an item after having bought a photo"

**Comment by CatmanIta** [comment]
I can't seme to reproduce it.. tested in multiple ways. Maybe it has something to do with the mobile device?

**Comment by FrancyCavallari** [comment]
@CatmanIta be careful the Issue title is not correct... it seems to happen when you reach 0 credits purchading the item (not taking the photo)...
... in example:
- you take a picture and you get down to 3 cookies
- you purchase the grass that costs 3 cookies
- your credits counter gets down to 0 but the grass does not appear in the scene (you lost the money)

**Comment by CatmanIta** [comment]
Yes, I did all kinds of combinations. That is the first one I tested (and with multiple items)

**Comment by FrancyCavallari** [comment]
Wassim was not able to reproduce the bug :-(

**Comment by FrancyCavallari** [comment]
We received more info about this bug from the online form:

**Feedback *
[if reporting a bug, please be as much descriptive as possibile]**
The game asks to take a picture of the dog for 20 Bones and then you get stuck.  You cant continue even een restarting.

**Device Details
[these data are automatically set if you open this form from the Antura app]**
{"AppVersion":"1.3.2.109","platform":"Android","systemLanguage":"Dutch","internetReachability":"ReachableViaLocalAreaNetwork","operatingSystem":"Android OS 10 / API-29 (QKQ1.191224.003/X505F_S001142_210804_ROW)","operatingSystemFamily":"Other","deviceModel":"LENOVO Lenovo TB-X505F","deviceName":"Lenovo Tab M10","deviceType":"Handheld","systemMemorySize":1864,"screenWidth":1280,"screenHeight":800,"screenDpi":160,"graphicsDeviceID":0,"graphicsDeviceName":"Adreno (TM) 504","graphicsDeviceType":"OpenGLES3","graphicsDeviceVendor":"Qualcomm","graphicsDeviceVendorID":0,"graphicsDeviceVersion":"OpenGL ES 3.2 V@415.0 (GIT@f345350, I0760943699, 1580221225) (Date:01/28/20)","graphicsMemorySize":512,"graphicsMultiThreaded":true,"graphicsShaderLevel":50,"supportsGyroscope":false,"supportsVibration":true,"supportsAccelerometer":true,"supportsLocationService":true,"supportsARGB32RenderTexture":true,"supportsAlpha8Texture":true}

**Player Profile
[these data are automatically set if you open this form from the Antura app]**
{"Uuid":"dae37013-4991-4700-8201-e3222357e56b","AvatarId":2,"Gender":1,"Tint":3,"Age":5,"IsDemoUser":false,"HasFinishedTheGame":false,"HasFinishedTheGameWithAllStars":false,"HasMaxStarsInCurrentPlaySessions":false,"TotalNumberOfBones":54,"ConsecutivePlayDays":0,"ProfileCompletion":0,"FirstContactState":{"phaseStates":[2,2,2,2,0,0,2,0,2,2,2,2,1,1]},"CurrentShopState":{"occupiedSlots":[{"slotType":0,"slotIndex":0,"decorationID":"mountain"},{"slotType":0,"slotIndex":1,"decorationID":""},{"slotType":0,"slotIndex":2,"decorationID":""},{"slotType":1,"slotIndex":0,"decorationID":""},{"slotType":1,"slotIndex":1,"decorationID":"tree3"},{"slotType":1,"slotIndex":2,"decorationID":""},{"slotType":1,"slotIndex":3,"decorationID":""},{"slotType":2,"slotIndex":0,"decorationID":""},{"slotType":2,"slotIndex":1,"decorationID":"prop2"},{"slotType":2,"slotIndex":2,"decorationID":""},{"slotType":2,"slotIndex":3,"decorationID":""},{"slotType":3,"slotIndex":0,"decorationID":""}]}}

**Comment by CatmanIta** [comment]
We did not have exception handling on issues when saving data. I have now wrapped it so it should not get stuck. This should fix the last issue, but the first one (0 cookies) is still not reproducible

**Comment by FrancyCavallari** [comment]
https://play.google.com/console/u/0/developers/6122529712980870033/app/4975496509321611897/user-feedback/review-details?reviewId=gp%3AAOqpTOEWEfUD5mVnvddTZbtAYGQDSYlGP6dBiXIF5-MzrQ5_nCcP0i7-jMxn4A7NDTi-2UpLajP0oH7gyjsEmA&corpus=PUBLIC_REVIEWS
