### ISSUE TITLE
[Dari] Be sure that diaritics are used only on Isolated form in minigames 

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#199]
_DancingDots_letterany
Egg_letterphoneme
HideSeek_letterphoneme_

Maybe also _ThrowBalls_letterany_ should be adapted

**Comment by FrancyCavallari** [comment]
Since Learn English we applied the following design rule for the names of minigames:

Each minigame name is composed with 2 parts: **<GameName_Type>**.
We have the following “**Types**” of games:

- LetterName (dealing with names of base letter and using only the isolated form)
- Alphabet (same as above but in alphabetical order)
- LetterForm (dealing only with the 4 forms of a letter according to its position)
- LetterAny (dealing with individual letters in any of their forms and any diacritic)
- LetterPhoneme (recognizing a letter only from listening a phoneme)
- LetterInWord (dealing with individual letters that are part of the word)
- BuildWord (compose a word using several letters)
- Word (dealing with full words)
- Counting (dealing with numbers and their wording)

NOTE: only the first 2 types use the letter name when pronouncing a letter name… all others will use the phonemes instead.

**Comment by FrancyCavallari** [comment]
We could create a new Type to handle diaritics on the isolated form of the letter:

- Diacritic (dealing with diacritics on the isolated form of the a letter)

**Comment by FrancyCavallari** [comment]
NOTE: we may need to adapt also the LetterForm variations because they will have to use Letter Names instead of Letter Sounds

**Comment by FrancyCavallari** [comment]
Maybe, instead of creating lots of minigame variations (and assessments) we could add some parameters to the Content Edition in order to define:
- if Diaritics should be combined with any Form or only appear on the Isolated Form (affecting LetterAny and LetterPhoneme variations)
- if LetterForm variations (and assessments) should use Letter Names or Letter Sounds

**Comment by CatmanIta** [comment]
Ok, here is what changed:

The edition config now has two more booleans.
![image](https://user-images.githubusercontent.com/3244662/146979448-94eb4e8d-253a-4926-b1e2-6a3b2d7b8cf6.png)

The first makes sure that LetterAny and LetterPhoneme variations (which will compare letters with and without diacritics) use Isolated letters only.

If OFF:
![image](https://user-images.githubusercontent.com/3244662/146979641-b8267f1c-7c52-454d-ac62-4ecde72b62d9.png)


If ON:
![image](https://user-images.githubusercontent.com/3244662/146979414-06226167-5668-434a-8190-5d97c5c36ce6.png)

Variations affected:
- Egg_LetterPhoneme
- HideSeek_LetterPhoneme
- ThrowBalls_LetterAny
- Assessment_LetterAny

Unaffected:
- DancingDots_LetterAny -  it was not selecting forms (filters are added to select letters with diacritics only, and no alterations/forms), so should it be unaffected?

(cont.)

**Comment by CatmanIta** [comment]
For what concerns the usage of Phoneme or Name with forms, it has been implemented for.
- FastCrowd_letterform
- ThrowBalls_letterform (the new variation)
- MissingLetter_letterform
- Assessment_CompleteWord_Form
- Assessment_MatchLettersToWord_Form

**Comment by FrancyCavallari** [comment]
Play Name sound with Forms should be implemented also for all _buildword games and similar assessments.

**Comment by FrancyCavallari** [comment]
And if "Diacritics only on Isolated" is true then all _buildword and _letterinword should avoid using letters with diacritics as wrong answers.

**Comment by CatmanIta** [comment]
For Play Name sound with Forms:

I had to change most minigames to the new GetVocabularySoundType method that lets the teacher decide what kind of sound to use based on the variation.

All the games that had these variations have been updated.

   - Egg_buildword
   - FastCrowd_buildword
   - MixedLetters_buildword
   - ThrowBalls_buildword
   - Balloons_letterinword
   - MakeFriends_letterinword
   - MissingLetter_letterinword
   - Tobogan_letterinword
   
   And for the assessments:
   - CompleteWord
   - WordsWithLetter
   - MatcheLettersToWord

Here is an example: what we do is, based on the variation, decide what kind of sound we want.

![image](https://user-images.githubusercontent.com/3244662/147228082-d43d5f45-2017-4f2d-a986-c7066402d85e.png)

**Comment by CatmanIta** [comment]
> And if "Diacritics only on Isolated" is true then all _buildword and _letterinword (and similar assessments) should avoid using letters with diacritics as wrong answers.

(still missing this, will keep this open)

**Comment by CatmanIta** [comment]
Removed diacritics when "Diacritics only on Isolated" is true for all BuildWord and LetterInWord games and assessments:

- Egg_buildword
- FastCrowd_buildword
- MixedLetters_buildword
- ThrowBalls_buildword
		
- Balloons_letterinword
- MakeFriends_letterinword
- Tobogan_letterinword
		
- Assessment_OrderLettersOfWord
- Assessment_CompleteWord
- Assessment_MatchLettersToWord
		
		
Note that I did not do this for **MissingLetter_letterinword** as it was already excluding all diacritics.

**Comment by FrancyCavallari** [comment]
**MissingLetter_letterinword** should be like the other games... and its filter to excluding all diacritics is not working
