### ISSUE TITLE
[PS DB] PS 1.1.1 has 1 single minigame instead of 2

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#207]
Only ColorTickle_lettername is present even if Maze_letername is correctly set in the PS DB
![image](https://user-images.githubusercontent.com/17926293/146356456-a7aaa03a-2c4d-45d5-99dd-6b42bfc5cd26.png)

**Comment by FrancyCavallari** [comment]
In the Console Log, the following warning appears:
`Could not select the requested number of 2 minigames for play session 1.1.1 (only 1 are available)`

**Comment by FrancyCavallari** [comment]
Ok, I found that Maze_letername minigame was disabled in CommonDB_MiniGame...
![image](https://user-images.githubusercontent.com/17926293/146357060-ad81ad4e-5fec-4510-9a2a-28a2d9260e92.png)
... but activating it does not solve the problem.

In fact Dari Content Edition is using Arabic_Minigame_Previous (???)
![image](https://user-images.githubusercontent.com/17926293/146358121-e4cd2d01-059a-42dd-a488-8d45ebd50e2c.png)

**Comment by FrancyCavallari** [comment]
I imagine we will need a specific MinigameDB for Dari, because we will need specific variations of some games to avoid mixing Forms and Diacritics

**Comment by CatmanIta** [comment]
We realized that we don't really need  the 'Active' flag anymore, so we can just check the PS to define whether a game can be active or not

**Comment by CatmanIta** [comment]
Also, this means we need just ONE minigame DB

**Comment by CatmanIta** [comment]
Note that Maze was not Active because we had removed it due to it not working with latin letters. It will be available now instead.

Now, "Active" defines whether a MiniGame variation should be used or not (we may not want to use MiniGames anymore as we develop, like we did with Maze)

It is however the PS DB that defines whether a MiniGame can actually appear in the edition. If it appears at least once in any PS, then it is added to the selectable minigames

**Comment by FrancyCavallari** [comment]
The new system is cool... but for some reason several used minigame are not set to Active!
i.e. both minigame of PS 1.5.1 (FastCrowd_letterform and MissingLetter_letterform) are not active
![image](https://user-images.githubusercontent.com/17926293/147010394-fc7533c1-223f-4713-968c-95247ebd8f51.png)

**Comment by FrancyCavallari** [comment]
Ok, I activated all (?) needed minigames in CommonDB_MiniGame and now they are present!
