### ISSUE TITLE
[Dari] The letter "ye" always appears in isolated form even when the medial/initial should be used

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#210]
"nose" (with the correct writing on the right):
![image](https://user-images.githubusercontent.com/17926293/146757976-5ec8c015-6484-49a6-9b39-49d15aa2e771.png)

the same happens in "juice"
![image](https://user-images.githubusercontent.com/17926293/146759024-7f1b5bb5-45dd-48ef-9bec-07fc8534fc66.png)

**Comment by CatmanIta** [comment]
This is the "farsi yeh" character, which is not handled in the ArabicFixer. We need to do it ourselves
