### ISSUE TITLE
[ThrowBalls] Create ThrowBalls_letterform variation

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#212]

**Comment by CatmanIta** [comment]
![image](https://user-images.githubusercontent.com/3244662/146994521-fedbe534-4673-498c-9a7e-a219aeff274e.png)
![image](https://user-images.githubusercontent.com/3244662/146994540-93d2bb44-246a-4ea3-a180-838c77cc8436.png)


The game will use no diacritics and may have any letter with any form.
