### ISSUE TITLE
[preview_Teacher] Modify WorldData Tester output to simplify copy & paste in the WordDB/PS DB 

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#224]
Since we now use the PlaySessionLink, it would be great to get also the output with all words (in the same order of the DB) and for each word the World/Stage in which they should appear... it is feasable without too much effort?
![image](https://user-images.githubusercontent.com/17926293/148921816-c50282e6-f021-4b35-bf30-6dd29bf35753.png)

And about the current ouput format... it would help to add a simbol (i.e. D) to know which words have a drawing assigned... something like this:

Words for group 1: 10 (tot 10/283):
ball (توپ) D
leg (پا) D
shoes (بوت) D
water (آب) D
iron (اتو)
berry (توت)
grandpa (بابا) D
fever (تب)
reward (ثواب)
blanket (پتو)

**Comment by CatmanIta** [comment]
Here is the Drawings output example:

Words for group 1: 10 (tot 10/283):
(With drawings: 5/10):
ball (توپ) D
leg (پا) D
shoes (بوت) D
water (آب) D
iron (اتو)
berry (توت)
grandpa (بابا) D
fever (تب)
reward (ثواب)
blanket (پتو)

**Comment by CatmanIta** [comment]
And the output example for the play session links (logged after the previous report)

PLAY SESSION LINKS:
airport (میدان هوایی), WordsStage5
apple (سیب), WordsStage4
apricot (زردآلو), WordsStage6
arm (بازو), WordsStage3
aunt (خاله), WordsStage6
autumn (خزان), WordsStage3
back (کمر), WordsStage6
ball (توپ), WordsStage1
banana (کیله), WordsStage6
bank (بانک), WordsStage6
beach (ساحل), WordsStage6
bear (خرس), WordsStage4
bed (تختخواب), WordsStage2
bedroom (اتاق خواب), WordsStage6
bee (زنبور عسل), WordsStage6
belly (شکم), WordsStage6
bicycle (بایکسل), WordsStage6
bird (پرنده), WordsStage5
book (کتاب), WordsStage6
box (جعبه), WordsStage5
boy (پسر), WordsStage4
brain (مغز), WordsStage5
bread (نان), WordsStage2
breeze (شمال), WordsStage6
brother (برادر), WordsStage3
bus (سرویس), WordsStage4
cake (کیک), WordsStage6
camel (شتر), WordsStage4
