### ISSUE TITLE
[ThrowBalls_letterany] Letters without diacritics appear in the game... and they have no phoneme sound

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#227]
Since the game is about listening to the phoneme (and watching its visual) and recognizing it... we should use only letters with phoneme sound. In the case of Persian / Dari that means we should use only letters with diacritics.

I still need to check all other _letterany and letterphoneme games, but I suspect this is a common issue to all these type of games.

**Comment by FrancyCavallari** [comment]
As expected the same problem is present in ...

Egg_letterphoneme (the letter on the left has no phoneme)
![image](https://user-images.githubusercontent.com/17926293/149236886-dd40cb5d-66e2-4350-b2e6-a00bccb4594f.png)

Hide&Seek_letterphoneme (the letter on the right has no phoneme and it's the correct answer)
![image](https://user-images.githubusercontent.com/17926293/149237334-1342345d-6093-4393-9bac-38dd163931c4.png)

**Comment by FrancyCavallari** [comment]
Maybe the simplest soluton for these type of games would be to filter only letters that do have a Phoneme Sound... this way we automatically exclude all letters without Diacitics in the case of Dari

**Comment by CatmanIta** [comment]
Filtering based on whether we have a phoneme sound is not optimal, as that requires trying to load the data (as all letters have their audio ID set, even if the audio is not there).

I think it is better to add a "PhonemesOnlyOnDiacritics" flag and use that
