### ISSUE TITLE
[Maze] Letter Variations are not used in the game

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#232]
We should clarify if we want the players to write also characters like hamza, yeh_hamza, lam_alef.
Note: alef_maddah is not more a Letter Variation (it has been changed to be a basic letter since it appears in the Dari alphabet)

**Comment by CatmanIta** [comment]
Enabled all letter variations. Note that all editions after we merge this will need shape data!

**Comment by FrancyCavallari** [comment]
It's working fine... better do it also for Color Tickle

**Comment by CatmanIta** [comment]
Done!
