### ISSUE TITLE
[Maze] minor visual bugs on the top part of the screen

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#233]
Getting close to top border of the screen I noticed a couple of minor visulal bugs with the strokes.
Here you have an example... everything works fine but when I have to trace the second stroke there no dotted line:
![image](https://user-images.githubusercontent.com/17926293/149550316-8aaf0e70-267e-4c39-9e01-b6ca0c227d00.png)

I noticed something similar also with another letter that has the dots close to the top border... maybe it's a Z-fight problem ?

**Comment by CatmanIta** [comment]
Yes, it is, as the camera is not ortographic. I tried to reduce it as much as possible, but letters that get too high pose a problem still.

It would be better to change the center pivot of such letters to be lower, can you do that?

**Comment by FrancyCavallari** [comment]
I move the center pivot... and it seems to be fixed now!
