### ISSUE TITLE
[Daily Reward] Skipping quickly the game freezes with a red error on Android

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#238]
To be re-tested after #237 is fixed

**Comment by CatmanIta** [comment]
Check after the new fix on the map bug

**Comment by FrancyCavallari** [comment]
I tested it and I have a different issue on Android:
if I spam the cookies on the Daily Reward and keep bashing the screen during loading it... I reach the map, the game is running but most of the UI is not responding (I can only touch a PS and start it)
I'll try to reproduce it in the Editor

**Comment by FrancyCavallari** [comment]
I confirm the issue is present also in the Editor: bashing the center of the screen during loading all Map UI (except the PS) become unresponsive.

**Comment by CatmanIta** [comment]
Is this on Arabic?

**Comment by FrancyCavallari** [comment]
I tested on Antura Afgha (Editor) today...
... and I can't remember if Andoird was Arabic of Afgha.
Better you check it on the latest Afgha!

**Comment by FrancyCavallari** [comment]
Just re-tested it... it was present in Arabic Android too!

**Comment by FrancyCavallari** [comment]
I was able to reproduce it in the Editor also without passing by the Daily Reward (from Home directly to the Map)...
... so I suspect it's a problem with the Map accepting input before being eady to handle it correctly

**Comment by CatmanIta** [comment]
Don't worry, fixed

**Comment by CatmanIta** [comment]
(it was exactly that, it's due to the game selector being opened and closed as you click on the first playsessio)

**Comment by CatmanIta** [comment]
I have backporter it to Arabic too
