### ISSUE TITLE
[Egg_buildword] listening to the letters a third time is annoying

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#267]
better remove the name of the letters when they jump out of the egg, keeping only the full word

**Comment by FrancyCavallari** [comment]
Now the word is pronounced too early, much before that the full word appear...
... maybe we can play a SFX when each letters jumps out of the egg and the the word when the word jumps out (like it was before)

**Comment by CatmanIta** [comment]
The Jump SFX sounds fun to me, even if it's always the same!
