### ISSUE TITLE
[FastCrowd_buildword] The worng form of the correct letter is accepted ... and it should not!

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#271]
![image](https://user-images.githubusercontent.com/17926293/162416870-a897f004-8207-4d83-9c56-b2a2134e4a92.png)

![image](https://user-images.githubusercontent.com/17926293/162416949-098d89cd-a955-40de-9db4-940b955eafee.png)

![image](https://user-images.githubusercontent.com/17926293/162417105-3efbf72b-8382-4d86-b8d4-381071644e64.png)

![image](https://user-images.githubusercontent.com/17926293/162417168-636c0cc9-c869-47aa-af27-05c8c2a7d3a5.png)

**Comment by FrancyCavallari** [comment]
Same problem is present in Assessment_CompleteWord
So we should check all games and assessments...

**Comment by CatmanIta** [comment]
Fixed. I found and fixed the same issue in:

Egg_BuildWord
ThrowBalls_BuildWord
ThrowBalls_MultiLetterForm

MixedLetter_BuildWord was already working correctly

Assessment_CompleteWord actually seems to work for me (and it was already matching correctly), can you find a case in which it does not?

**Comment by FrancyCavallari** [comment]
Maybe I was wrong and the problem is present in Assessment_WordsWithLetter, @CatmanIta can you please check?

**Comment by FrancyCavallari** [comment]
I just tested Assessment_WordsWithLetter and it seems ok
