### ISSUE TITLE
[Edition Selector] After switching Edition, the PLAY button is wrongly placed

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#280]
![image](https://user-images.githubusercontent.com/17926293/165283988-86a45c1e-c463-4253-b9ec-089f9fce5545.png)

NOTE: it may happen only if the number of profiles is different between the previous and the current version

**Comment by StefanoCecere** [comment]
@CatmanIta there is another problem when switching edition: the player icon is wrongly selected (actually it is UNSELECTED) and if you play the game is broken... we should automatically select the first player

**Comment by CatmanIta** [comment]
Fixed that bug
