### ISSUE TITLE
[Dari] [Drawings] Create and import localized drawings of Days for Afghanistan... or remove them!

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#288]
![image](https://user-images.githubusercontent.com/17926293/166660088-6a09c210-c65b-41c3-828a-ba1fe6bf48c0.png)

Sunday is the first day of the week in Afghanistan and the drawings should use Afghan names... 
... or we could remove the Days from Dari/Pashto edition.

**Comment by FrancyCavallari** [comment]
@StefanoCecere let's talk about it tomorrow...

**Comment by FrancyCavallari** [comment]
We have also an issue with the Days drawing in English, they are using French drawings instead fo English ones.
Maybe better we check alll languages....

**Comment by StefanoCecere** [comment]
done. we should check every game, now

**Comment by FrancyCavallari** [comment]
I moved it back to In Progress to check all the games...
