### ISSUE TITLE
[UI] "Are you sure?" dialog displays twice the same message...

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#289]
![image](https://user-images.githubusercontent.com/17926293/166662823-bd72610c-b491-4107-a552-bf2d7a1b4ca8.png)

Is it displaying both Learning and Native language?
If so, it does not make sense in the 2 languages are the same (that is in any Learn to Read edition)

**Comment by CatmanIta** [comment]
It's actually showing Learning on both, but that is a bug.

Instead, that small text below is tied to ShowHelpText and is supposed to show the Help Text.

I'm changing it so that it uses the native / learning text instead (as we show it for the player), and do not show the below one if they are both the same. Is that ok?

**Comment by FrancyCavallari** [comment]
Displaying the Native is not really needed... the Native audio is played anyway!
I would remove/disable the second line... we don't need help text for such a simple Dialog.

**Comment by CatmanIta** [comment]
All the usages of "Are_You_Sure" were set to override the default keeper mode and instead use LearningNoSubtitles. It was probably because we did not want to tell it twice? 
I removed the overrides.

**Comment by FrancyCavallari** [comment]
Linked with #336 : in the Reserved Area the Native Language should be used instead of the Learning one.

**Comment by FrancyCavallari** [comment]
Still present in the Antura Space (trashing a decor from the shop)...
![Image](https://user-images.githubusercontent.com/17926293/172598562-4a4fdf49-e391-401f-af99-553240c99402.png)

It also happens when quitting a minigame (even if it's not much vbisible because of the pause menu ovelap) 
![Image](https://user-images.githubusercontent.com/17926293/172600806-5f1f241d-07e8-46f1-8d39-6c441cb13cd8.png)

So we should check every where this popup is used through the game...

**Comment by FrancyCavallari** [comment]
Apart from the Reserved Area in which we use the Native Lang, all over the game we always use the Learning Lang, so the popup should appear in the Learning Lang and the audio played in Learning then Native Lang...
...but without the subtitles box on the top of the screen!

**Comment by StefanoCecere** [comment]
are you sure you want all dialogs in learning language + double audio?
i would just make them all native language.

**Comment by FrancyCavallari** [comment]
all the game uses double audio (except Reserved Area)... so making anything different would feel weird.
Better keep the double audio (as it was in the original Learn English and Learn French)
