### ISSUE TITLE
[Minigame Launcher] Not all minigames/variations are present...

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#295]
This is Learn French from Gplay...
![image](https://user-images.githubusercontent.com/17926293/166893367-8ef910cc-f79d-4565-a0f6-790ea85cba5a.png)

... the minigames/variations marked in red are not currently present in the Launcher!

**Comment by FrancyCavallari** [comment]
I tested it in Learn French and Learn English ... and the problem is present in both!

The minigames missing are 
- MissingLetter_Phrase
- ReadingGame_word
- all Song_word_xxx

**Comment by FrancyCavallari** [comment]
Note the minigames are not present in the Journey (i.e. if you go to PS 2.17.200 you don't have any minigame to play)...
... but I don't see any error when importing the PS DB

**Comment by StefanoCecere** [comment]
"A MiniGame can be selected for play only if it is found inside any PlaySession of the current edition."

**Comment by CatmanIta** [comment]
Yes, that's how it works, as  you cannot unlock it at all if it is not found in the Journey, so we had a requirement of all minigames to be in the Journey too.
