### ISSUE TITLE
[iOS][Android] On the device, the game does not start the first time you launch it after installation

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#304]
The game gets stuck on the black screen after the splash screens.
After killing the app, if you relaunch the game it starts correctly.

NOE: I experienced it both on Andorid and iOS.

**Comment by ajzbrun** [comment]
I was checking on this issue, and I find out that the only error thrown when the game doens't start, is in the method LoadSettings() of the Antura.Core.AppSettingsManager class.

This is the specific error catched by the Android Logcat
`2022/05/24 13:27:35.896 22129 22211 Error Unity NullReferenceException: Object reference not set to an instance of an object.
2022/05/24 13:27:35.896 22129 22211 Error Unity   at Antura.Core.RootConfig.get_ContentEdition () [0x00000] in <00000000000000000000000000000000>:0 
2022/05/24 13:27:35.896 22129 22211 Error Unity   at Antura.Core.AppSettingsManager.LoadSettings () [0x00000] in <00000000000000000000000000000000>:0 
2022/05/24 13:27:35.896 22129 22211 Error Unity   at Antura.Core.AppManager+<InitCO>d__36.MoveNext () [0x00000] in <00000000000000000000000000000000>:0 
2022/05/24 13:27:35.896 22129 22211 Error Unity   at Antura.Core.AppManager.BlockingCoroutine (System.Collections.IEnumerator c) [0x00000] in <00000000000000000000000000000000>:0 
2022/05/24 13:27:35.896 22129 22211 Error Unity   at Antura.Core.AppManager.Awake () [0x00000] in <00000000000000000000000000000000>:0 
`

I'll keep trying some workarounds to see why exactly does this break.

**Comment by CatmanIta** [comment]
We found out that the deletion of profiles was not actually deleting all preferences, I fixed that and now this issue appears also in the editor.
