### ISSUE TITLE
[AlphabetSong] the minigame does not work in Learn English

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#305]
It seems that it cannot find AlphabetSong.mp3 and AlphabetSong.akr files (I guess in the English folder)... and it makes sense because those files were only present in Italian and Spanish because the songs did not support languages until last week.

I copied the AlphabetSong.mp3 and AlphabetSong.akr files into English/Audio/Songs folder... but I cannot fix the addressables.
If I use the tool it seems to fix only Polish language addressables and I don't knwo how to fix English instead.
![image](https://user-images.githubusercontent.com/17926293/168572948-c206c9d1-5a04-4ee7-b675-4a69ec718fd7.png)

**Comment by CatmanIta** [comment]
Also: let's fix the addressable fixer so it checks all languages
