### ISSUE TITLE
[Editions] Create Learn Romanian and Learn Hungarian editions... as well as the corresponding language folders

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#309]

**Comment by FrancyCavallari** [comment]
@ajzbrun Please add also Learn German (edition and language) and Russian (language)

**Comment by ajzbrun** [comment]
The Romanian, Hungarian and German learn editions are created basically. @FrancyCavallari let me know when the spreadsheets are ready so I can finish setting up those editions and do the initial import.
