### ISSUE TITLE
[Book] The UI Font is used instead of the Learning Font in a few places in the book

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#312]
![image](https://user-images.githubusercontent.com/17926293/169869075-e11cabb3-be9c-4ff3-86af-3d5280524eb5.png)

![image](https://user-images.githubusercontent.com/17926293/169868917-f83e67bd-261d-4882-88a2-fcd168a4ae6e.png)

**Comment by StefanoCecere** [comment]
@CatmanIta i changed some text updates from SetTextUnfiltered() to SetText(), otherwise the font isn't updated...
it seems we don't have any sideeffect
