### ISSUE TITLE
[Tool] Modify the 'preview_Antura' scene to test all animations

### ISSUE THREAD

**Issue by ajzbrun** [vgwb/Antura#321]
Modify the 'preview_Antura' scene (on path 'Assets\_manage\preview_Actors') to test all the animations on the dog model, and in the future in the cat model too.

**Comment by StefanoCecere** [comment]
the animations states work.. but i don't understand well the "animations" buttons grid: they are toggle buttons (not standard ones) and the Doc crashes after playing with these buttons

**Comment by ajzbrun** [comment]
The antura_Preview scene was fixed, now all the rewards are working as well as the animations. Regarding the animations toggle buttons, yes: indeed, they're toggle buttons so you can test more than one animation at a time.
After a few tests, I've seen no crashing at all @StefanoCecere 
Please let me know if it's still crashing
