### ISSUE TITLE
[Dari] some letters/words are not of good quality once imported in the game

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#325]
i.e. PE.mp3 (https://github.com/vgwb/Antura/commits/main/Assets/_lang_bundles/persian_dari/Audio/Letters/pe.mp3) is very bad while the original recording in WAV was good (https://drive.google.com/file/d/19SAh_uRBqekpSkHKZ_8bW0aYPeAv1vrW/view?usp=sharing) 

We re-recorded a certain amount of letters and words but the problem is still present... can it be caused by the MP3 compression?

**Comment by StefanoCecere** [comment]
coudl have been a problem in the audio mixer levels. let's try now

**Comment by FrancyCavallari** [comment]
Still present... It's bad quality also when listening the file in the Editor and even listening to the MP3 file with any audio player

**Comment by FrancyCavallari** [comment]
The most urgent audio ti fix are Letter and Words in this folder:
https://drive.google.com/drive/folders/1rHWRdVB36IMr8O1XATQonMD6ZL2ECYs1?usp=sharing
