### ISSUE TITLE
[Language Selection] Improve the UX by ordering elements

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#328]
Right now the order in which the questions is played is the same than the language buttons... and it's not taking into account the player actions and eventually it's device default language.
![image](https://user-images.githubusercontent.com/17926293/170464302-c5658e69-d884-4ee4-8f1e-3e14adeb5224.png)

Let's design well how the buttons should be ordered and in which order the question should be played in all languages?

**Comment by FrancyCavallari** [comment]
I was able to set a meaningful order for the button using the list in Config Root.
But we can improve the animation/initial scrolling in order to maximize the probability of having the best choices on screen for any player:
1. scroll to the device language the first time you play (if supported), otherwise scroll to English
2. if you come back to change language, scroll to the previously selected language 

About the Question it could make sense to:
1. start with the device language the first time you play (if supported) otherwise English
2. if you come back to change language, start with previously selected language and then use the device lanaguage (if supported)
3. sort randomly the other languages to show variety in the supported languages  

anyway, let's talk about it @CatmanIta

**Comment by FrancyCavallari** [comment]
One more thing, when selecting a language/button, the Language Name should be pronounced in that same language (Native Language) calling the the Text Entry "Language_Name".

**Comment by CatmanIta** [comment]
We decided to not sort the languages randomly during the voice part, it feels a bit weird to me!

**Comment by StefanoCecere** [comment]
considerazioni: "Qual è la tua lingua madre?" è brutta... meglio "Che lingua parli?" e poi non sarebbe meglio scrivere tutto in maiuscolo questi dialoghi? di fatto usiamo lo le maiuscole in tutti i percorsi didattici

**Comment by FrancyCavallari** [comment]
Abbiamo già registrato le voci in tutte le lingue con questa frase... non la cambierei, almeno per ora.
Non sono d'accordo riguardo ad usare le maiuscole, non è un contenuto didattico, è un dialog come tutti gli altri del gioco.

**Comment by FrancyCavallari** [comment]
Linked with #360
