### ISSUE TITLE
[Loading] The App takes 15-20 seconds to load on my new Android phone

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#330]
We must find a way to speed up loading

**Comment by StefanoCecere** [comment]
bypassing all addressables preloading? can we load them on demand?
i would try... it would simply all appmanager initialization, also

**Comment by CatmanIta** [comment]
We preload everything to make sure that they are available when requested by the many places that just access the data in the game. We can surely move some pieces later, but it requires a big effort, changing many of the existing games.

I have an idea: we could try using the code I made to make the loading synchronous even if it is using coroutines, that could help.

**Comment by CatmanIta** [comment]
I did some measuring and it does not seem to be related to the preload. We preload only 5 MB now and the delay is not happening during the preload, but before, when the bootstrap scene loads.

**Comment by FrancyCavallari** [comment]
Android build 215 (Multi Edition - Dev) takes 6-7 seconds to load on my phone...
... we launched a new build to test Multi Edition - Release

**Comment by CatmanIta** [comment]
We think that the slowdown happens during the load of the Bootstrap scene, I am doing some tests to see what I can find out

**Comment by CatmanIta** [comment]
Song still needs work

**Comment by FrancyCavallari** [comment]
Both Alphabet Song and 123 Song are not working at the moment

**Comment by CatmanIta** [comment]
I re-added the loading, now the data is loaded when the song game is opened. We need to test the speed of this, however, as I suspect it will take a few seconds anyway since it is loading the different files!
