### ISSUE TITLE
[Content Selection] When selecting a content edition, the "Learn_xxx" audio key should be played in the Native Language 

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#338]
I.e. if I select Italian as Native Lang and then I select Learn English... I should hear "Impara l'inglese" when I press the button
![image](https://user-images.githubusercontent.com/17926293/170722954-787cbda9-ac85-4642-a97d-1cc0c5341bab.png)

**Comment by StefanoCecere** [comment]
mi tolgo da questa issue, perché con la gestione di Game_Title_2 che supporta il multi edition (a seconda della lingua, cambia la traduzione) è troppo complesso per me
