### ISSUE TITLE
[Json Import] Slow recognition of new generated jsons from Google sheets to the Manage Database scene

### ISSUE THREAD

**Issue by ajzbrun** [vgwb/Antura#340]
We were looking with @StefanoCecere that Unity takes some time to recognize the changes in the generated json files (from Google sheet), both in Vocabulary and PlaySession.
The problem was detected because I make an import from the Rumanian and Hungarian google sheets that had missing columns (so it obviously was throwing errors on scene database import), but when the sheets were fixed with all the missing columns, we did the reimport of the json files and when tried to import them from the scene, the same error was appearing (the one of the missing columns).

After a while, re checking that the jsons were valid, and the columns were present, and so on, when we tried to reimport again (without any changes), it imported the jsons without errors.

Stefano had the idea of make the import from the google sheets direct into the database (without going through the json files), which could be a good solution to this.

**Comment by StefanoCecere** [comment]
it's good but there is just a problem: method RegenerateEnums() in `DatabaseLoader` wants to parse the json file to regenerate the enums.
it should be refactored or eliminated.
@CatmanIta ?

**Comment by FrancyCavallari** [comment]
@CatmanIta let's add a single import button for everything into the scene... here!


![Image](https://user-images.githubusercontent.com/17926293/176393189-968313ff-9c25-4b10-84f5-9362274f99cb.png)

**Comment by ajzbrun** [comment]
Also, now that I see it, I think that makes sense to delete the red button "Import All Json Data" from the scene...

**Comment by FrancyCavallari** [comment]
@ajzbrun is right, we should get rid of the 2 obsolete buttons in the scene!
![image](https://user-images.githubusercontent.com/17926293/176423814-bcb37164-c65c-4aa3-b684-12347908f71b.png)

**Comment by CatmanIta** [comment]
Doing
