### ISSUE TITLE
[LetterData] How can we support languages in which a letter is represented by 3 chars/3 unicodes?

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#343]
I.e. in Hungarian (https://en.wikipedia.org/wiki/Hungarian_alphabet) "Dzs" is a letter!!!

**Comment by CatmanIta** [comment]
Also, we'll make sure to never use the "Isolated" text, but always get it from the UNICODES, to avoid errors

**Comment by FrancyCavallari** [comment]
@CatmanIta apart from supporting multi-char letters, we also have to support correctly multi-char letters that include another letter.
I.e. in Hungarian all the following one are 3 valid letters:
D
DZ
DZS

So I imagine the Hungarian Language Helper will have to prioritize/manage them correctly in order to split a word into letters

**Comment by FrancyCavallari** [comment]
@CatmanIta once it's done we should also check that the Preview_Teacher can handle it well

![Image](https://user-images.githubusercontent.com/17926293/177486829-fda712d4-706c-4941-bb30-222d5e6b974d.png)
