### ISSUE TITLE
[Egg_letterphoneme] The animation when touching the egg is too short (cut) 

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#345]
The same anim is played at the beginning of each round to present the letter you have to find (question) ... and it's so short that the audio of the question overlaps with the audio of the first possible answer.
![image](https://user-images.githubusercontent.com/17926293/171613577-82a0f701-bded-47a3-8d0c-95a679f99a60.png)

NOTES: 
- in Egg_buildword the animation of the "?" on top of the egg lasts during all tutorial explanation/animations... most likely it should be the same in Egg_letterphoneme.
- I tested it in Dari and Arabic: in Dari the problem wes present also during the presentation of the question (but then I tested again and it was not present), while in Arabic was only visible when you touch the egg to listen again

**Comment by CatmanIta** [comment]
Was it like that before? Or was it only during the tutorial? (The code is really ,really messy with this game, I'm trying to touch as little as possible!)
