### ISSUE TITLE
[MakeFriends] on very wide screens the drop zone is so high that goes behind the subtitle... 

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#346]
... making it impossible to drop a letter until the tutorial dialogs are over:
![image](https://user-images.githubusercontent.com/17926293/171616220-0d9ed49f-18e5-4879-90d8-293603a59b61.png)

NOTE: on a 16:9 or 16:10 screen the dropzone is placed in a lower position... maybe we can compute/anchor differently the dropzone to make its position less dependent of the aspect ratio
![image](https://user-images.githubusercontent.com/17926293/171616546-63afc79d-12ae-41bc-9828-cf01e60fcde8.png)

**Comment by CatmanIta** [comment]
I changed how the UI scaling works in the game, as it's better to keep the same height instead of width.
I also made the drop zone a bit smaller, and more consistent in different aspect ratios.

At 21:9 it now appears as such:


![Image](https://user-images.githubusercontent.com/3244662/176451865-f908b998-5eeb-4b1b-b0ed-0862ff5686c4.png)

**Comment by FrancyCavallari** [comment]
Testing it in LearnTo Read Arabic... and I don't see the Drop Zone...
... apart that most diacritics are outside of the bubbles in the buttons below.

![Image](https://user-images.githubusercontent.com/17926293/176459379-8e91cd1c-34f4-4bca-911b-36715516a00e.png)

**Comment by FrancyCavallari** [comment]
The DropZone appears only after you start dragging a letter...


![Image](https://user-images.githubusercontent.com/17926293/176460078-2ee2d1ac-2ec7-460d-bd9e-95b60e3749eb.png)

**Comment by CatmanIta** [comment]
I saw that too but thought it was intended, as it started like that before doing this change! Weird. I'll look into it

**Comment by CatmanIta** [comment]
Fixed
