### ISSUE TITLE
[Addressables] in Learn to Read Persian_Dari, the Game_Title audio is not played in the home page on Android

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#347]
I had the same problem in the Editor, and fixing the Persian_Dari addressables was not enough to fix it.
It was able to solve it by selecting AppConfig - Multi Dev and pressing Configure as Active & Rebuild Addressables.
I pushed all the Addressables Asset Groups (including Persian_Dari) but the problem is still present in the Android version delivered by the cloud build (v222). 

Is there a way to force the Cloud Build to rebuild all addressables?

**Comment by CatmanIta** [comment]
I think it's solved now, it was for some reason not handled correctly in your build.

I also made it that switching editions fixes all addressables, so you can just click that button if you prefer!
