### ISSUE TITLE
[Content Selection] The text labels of all Learn to Read editions are wrong

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#352]
Both in Arabic and Dari the black text label of the Learn to Read edition is using the wrong text entry. 
It's using **Learn_Arabic** (or **Learn_Persian_Dari**) instead of **Learn_Read**
![image](https://user-images.githubusercontent.com/17926293/172347175-8a493512-ddfe-4877-b99f-abcfe5631b0d.png)

**Comment by CatmanIta** [comment]
![image](https://user-images.githubusercontent.com/3244662/172579531-25339c70-e0fd-42b1-ae61-4d3d561abd4a.png)

I got this now. The language below has a different text for me in arabic, tho, is it an issue?
