### ISSUE TITLE
[Audio] Obsolete English recordings are still present in the game  

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#353]
We removed every reference to "English language" from the script/voices but we still have the old audio files when playing Learn English edition:

- End_Scene_1_2
- Intro_Welcome
- Map_Intro
- Map_Intro_LB_Alphabet
- Map_Intro_LB_Animals

**Comment by FrancyCavallari** [comment]
2 audio files (Map_Intro_LB_Alphabet , Map_Intro_LB_Math) have not been recorded... so I asked the actress to record them in the coming days!

**Comment by FrancyCavallari** [comment]
I updated and committed 4 files:

- End_Scene_1_2
- Intro_Welcome
- Map_Intro
- Map_Intro_LB_Animals

As soon we receive the 2 missing files we'll update them:

- Map_Intro_LB_Alphabet
- Map_Intro_LB_Math

**Comment by StefanoCecere** [comment]
i dont' know what to do for this issue

**Comment by FrancyCavallari** [comment]
We received the 2 missing files and I asked Tabea to edit them... I'll import them as soos as I get them!
