### ISSUE TITLE
[End Scene] In Learn to Read editions the dialog End_Scene_1_2_Read is cut 

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#355]
The subtitle opens but it closes immediately... and the audio is not played at all.
It seem that the text appearing below ( End_Scene_2 ) may force the closing of the subtitle/cutting of the audio

**Comment by CatmanIta** [comment]
Are you sure about this? What language were you playing?
I had to add the dialog to arabic_legacy, as it was only added to arabic. I think that was the issue!

**Comment by FrancyCavallari** [comment]
Still present in Dari...

**Comment by CatmanIta** [comment]
The Read_1_2 file was not setup for Dari, I fixed the addressables for it, try again please!

**Comment by CatmanIta** [comment]
(no, that was Polish, I'm checking Dari now)

**Comment by CatmanIta** [comment]
![Image](https://user-images.githubusercontent.com/3244662/173825039-33655ed4-cf8a-458c-a556-9b697bd38852.png)

I see this, there is no text! 
It seems that persian_dari is placed at index 6, even if the language is at index 7, why is that?
