### ISSUE TITLE
[Parental Gate] What if the Native Language is the same than the Help Languange (English)? 

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#356]
In all Learn language editions we use both the learning language and the help language in the parental gate (unless they are identical)... and we avoid the Native Language so that children cannot access the reserved area (since we assume they cannot read the Learning Language).
But what if the Native Language is English (=Help Lang)? 
This is a screnshot from Learn French with Native set to English: as you can see the instructions are displayed in English as well because it's the Help Lang!
![image](https://user-images.githubusercontent.com/17926293/172948602-7402ed3c-cb6c-4910-b83a-474c238ecf3a.png)

Is it ok or should we manage differently this case?

**Comment by CatmanIta** [comment]
If Native == Help, we could maybe show only the Learning one. 
But, by doing so, teachers won't be able to access it unless they know the Learning language too.
We cannot find an unique solution, I fear, as if Native == Help we are saying that the language that the teacher knows best is the same language as the student's, so we cannot show a help message only for the teacher!

**Comment by FrancyCavallari** [comment]
Let's not change anything...
