### ISSUE TITLE
[Content Selection] Improve the visual of the book-buttons

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#364]
Yadire is producing the art for the content selector in Home

**Comment by FrancyCavallari** [comment]
Once defined the visual for the book-buttons in the Content Selection, we should also adapt the button in the Home
![image](https://user-images.githubusercontent.com/17926293/173311328-63e77b32-b061-4446-811e-c927960af26f.png)

**Comment by StefanoCecere** [comment]
@ajzbrun could you do this?

**Comment by ajzbrun** [comment]
@StefanoCecere for sure :)

**Comment by FrancyCavallari** [comment]
I proposed to Yadira to make the label frame a bit taller, moving the logo higher... 
... @ajzbrun you can start using the art Stefano mentioned but it's likely that Yadira will provide a new one soon.
Here you have the thread in Slack: https://vgwb.slack.com/archives/C036Q2YLWHF/p1654726249224369

**Comment by ajzbrun** [comment]
> I proposed to Yadira to make the label frame a bit taller, moving the logo higher... ... @ajzbrun you can start using the art Stefano mentioned but it's likely that Yadira will provide a new one soon. Here you have the thread in Slack: https://vgwb.slack.com/archives/C036Q2YLWHF/p1654726249224369

Oh, okay. Thanks for letting me know. I'll tell her to let me know when its ready

**Comment by ajzbrun** [comment]
@FrancyCavallari the new book icon is implemented

**Comment by FrancyCavallari** [comment]
@ajzbrun can we center better the logo on top part of the book?
![image](https://user-images.githubusercontent.com/17926293/173549926-a0df7713-2537-496f-8c82-d388b99eb586.png)
It should be moved a bot to the right and up

**Comment by FrancyCavallari** [comment]
We can also reduce the space between elements/books, so more books are visible without scrolling
![image](https://user-images.githubusercontent.com/17926293/173550520-269499e8-3ec1-4ec2-96a9-977ec4ea4eb5.png)

**Comment by ajzbrun** [comment]
nice suggestion, done @FrancyCavallari
