### ISSUE TITLE
[Dancing Dots] The UI buttons on the right are very small

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#384]
Not sure what happened... but now they appear like this:
![image](https://user-images.githubusercontent.com/17926293/175264209-df0284a5-481e-487e-95f9-889fcfcf32cb.png)

**Comment by FrancyCavallari** [comment]
This issue is present both in Arabic and Dari... and on all devices.

**Comment by CatmanIta** [comment]
Done, but leaving it open as I need to place it on the Main branch too
