### ISSUE TITLE
[Language Selection] At the first boot you can close the popup and get to home page without any Edition selected

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#395]
![image](https://user-images.githubusercontent.com/17926293/176789406-47810209-aca0-4228-8df7-002f4f68c493.png)

![image](https://user-images.githubusercontent.com/17926293/176789416-25b6e856-b620-4467-a675-56ea65dbc22d.png)

**Comment by FrancyCavallari** [comment]
You can still quit the section without selecting anything:
1. select a language
2. in the content selection screen press the Language button to go back
3. notice that in the Language Selection screen you have the X button to quit the section without selecting anything

**Comment by CatmanIta** [comment]
Ok, I rewrote it, seems to me it works correctly now in all cases!
