### ISSUE TITLE
check Reading_Game from autoplay

### ISSUE THREAD

**Issue by StefanoCecere** [vgwb/Antura#396]
when launched from game_ReadingGame scene with autoplay in SOng_word_nature
we have to click the keeper dialog to advance (usually it goes automatically)

**Comment by CatmanIta** [comment]
I don't see this happening, it plays correctly for me

**Comment by FrancyCavallari** [comment]
I cannot reproduce it now, @StefanoCecere can you please check if it's still happening to you?

**Comment by StefanoCecere** [comment]
solved
