### ISSUE TITLE
[Pashto] Maze has some issues (improve shape of rings)

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#398]
Right now some minigames do not work

**Comment by FrancyCavallari** [comment]
The shapes are done and they seem fine to me... but for some reason some strokes cannot be drawn successfully in Maze

**Comment by CatmanIta** [comment]
Regarding the number of rounds: it seems that Maz gets 5 letters, then plays the tutorial round, then 6 more rounds, so you see 7 letters instead!
I think we should reduce it to tutorial + 5 rounds, and select 6 letters (so the tutorial one is just the first).

**Comment by CatmanIta** [comment]
The large letters cut on the right is due to the rendering font, so it's not a problem of maze (you can see the same in the Book)

**Comment by CatmanIta** [comment]
I changed a bit the rings in the shape data, let me know if it gives issues still!

**Comment by FrancyCavallari** [comment]
The shapes of the rings may be improved
