### ISSUE TITLE
Add a column to letter data table to represent the splits of ligatures (such as Œ becoming O and E)

### ISSUE THREAD

**Issue by CatmanIta** [vgwb/Antura#403]

**Comment by CatmanIta** [comment]
I added an optional column, tested with French at the moment.


![Image](https://user-images.githubusercontent.com/3244662/181042473-63f59593-205a-4d1e-9dfe-d53bdb8b95b5.png)

**Comment by FrancyCavallari** [comment]
I copy here my comment in Slack:

se i riferimenti alle lettere in cui deve essere divisa una ligatura li scriviamo così non potremmo avere problemi con letter multi-char?
per es. in ungherese la lettera DZS fino a qualche anni fa era compsta da 2 lettere D+ZS ... adesso non credo che avremo problemi con l'ungherese ma lo dico solo per anticipare eventuali problemi futuri
dall'altra parte, adesso che ci penso, come bisognerá settare la LAM_ALEF in arabo? con gli id ("lamalef") o con le lettere ("لا")? perché con le lettere non si può scriverle vicine ma con 2 chars... vengono unite automaticamente da tutte le apps

**Comment by CatmanIta** [comment]
Valid points. I added commas to separate letters, and you need to use the ID, not the letter now.

**Comment by FrancyCavallari** [comment]
Checking about Lam_alef in Arabic languages....

**Comment by CatmanIta** [comment]
We need to do the same for Lam Alef (it has custom logic in the arabic fixer)

**Comment by FrancyCavallari** [comment]
Yes, it's confirmed that Lam_alef is a ligature in Arabic, Dari and Pashto

**Comment by CatmanIta** [comment]
It works, but we need to change FastCrowd BuildWord so that the word composer correctly merges the two letters to compose the Lam Alef

**Comment by CatmanIta** [comment]
Done, updated Dari, Pashto, Arabic tables.
