### ISSUE TITLE
Reward system breaks when PS are too many (for example, in Hungarian, creating the demo profile)

### ISSUE THREAD

**Issue by CatmanIta** [vgwb/Antura#406]

**Comment by FrancyCavallari** [comment]
The system does not break anymore... but now we have an incoherence:


![Image](https://user-images.githubusercontent.com/17926293/179951356-0a6a4a65-9706-43fe-a83f-41f19aca9d80.png)


The map suggests you'll get a reward for all LB (including the last ones)... but there is no rward for those LB!

**Comment by CatmanIta** [comment]
Yes, I just made sure it would not break. 
To change that, we should detect whether a PS reward is avaialble or not beforehand, which is not feasible at the moment and require some amount of work. I'll look into it.

**Comment by CatmanIta** [comment]
I can confirm that this is going to take a while, we need to change how the reward system works for this! We'd better wait and talk about it.

**Comment by CatmanIta** [comment]
We can give you some bones instead, that would be easier
