### ISSUE TITLE
[DiacriticsCombo] In Pashto the Editor uses the Arabic combos instead of the Pashto ones  

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#411]
![image](https://user-images.githubusercontent.com/17926293/177787926-4d47db62-1b18-45dd-a955-fce90a677676.png)

**Comment by CatmanIta** [comment]
The generation of the combo table must be performed manually via a flag in the code as of now, so I need to do it. We may want to add a button somewhere to trigger it manually maybe!

**Comment by FrancyCavallari** [comment]
I agree... a button somewhere to manually generate it makes a lot of sense
