### ISSUE TITLE
[Teacher Tester] in DataStatisticsTester, when printing Letters & Words the log gets truncated

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#413]
Please supports a log twice as long as currently supported

**Comment by FrancyCavallari** [comment]
my path is: 
C:\Users\cangi\AppData\Local\Unity\Editor

**Comment by CatmanIta** [comment]
Do this

![Image](https://user-images.githubusercontent.com/3244662/178678836-04666aa3-97dd-40d5-ab7b-809cc8910036.png)
