### ISSUE TITLE
improve editor list widgets

### ISSUE THREAD

**Issue by StefanoCecere** [vgwb/Antura#421]
expecially the minigames list: readable IDs

and if we coudl have a generic "search", even better

**Comment by CatmanIta** [comment]
I made the minigame list readable.
I've been looking for a ready search function tool but there is none, I would need to create a custom editor instead for that

**Comment by CatmanIta** [comment]
I managed to get a search function going and it works with minigame DB for now to test it. 
It only has an issue I cannot get rid of: it will save more data to the scriptable object due to the need for serializing the shown data, but if we can just ignore that I think it can be useful.
