### ISSUE TITLE
Make Maze Easier

### ISSUE THREAD

**Issue by CatmanIta** [vgwb/Antura#425]
Make colliders change size as you play to make the game easier

**Comment by FrancyCavallari** [comment]
Houston we have a problem... a much bigger problem! :-(
I asked my wife to play it on Android she barely succeded in writing one letter out of all the letters in a minigame.
Sometimes she seemed to draw correctly but the game still was giving a failed round without a clear feedback of why she failed.
Sometimes she raised the finger slightly before the last arrow, missing it... sometimes she did not raise the finger but the system did not recognize the last step of the trace, thus missing the last arrow.
We have to analyze the whole minigame in detail and find a way to improve it...

**Comment by FrancyCavallari** [comment]
I forgot to mention that the shape should be improved for some letters because two arrows are too close one each other.

**Comment by FrancyCavallari** [comment]
Another major improvement to make the game simpler would be to allow the player to draw a trace in more than one gesture (that is allowing to raise the finger and then continue from where you stopped or from the last valid checkpoint).
Let's talk about it...

**Comment by CatmanIta** [comment]
We decided to allow multiple strokes to finish the letter, and the animation has been updated to follow the spline.

**Comment by FrancyCavallari** [comment]
The game is much better now!
A few more improvements to make it "perfect" ;-)

- add rocket floating forward/backward animation every time it's still waiting for the player to draw
- remove timer and add 3 lifes for EACH letter/round (ideally we should not restart the letter after losing a life, like in Color Tickle, but we may have a problem with all the wrong writing staying on screen... ideally the failed trace, that is the last one, should disappear but all the previous ones (successfull) should be visible
- Let's try removing the yellow/green dot after the first successful trace (it does not move whre the rocket stands still)

**Comment by CatmanIta** [comment]
All done. We noticed that the dot behaves weirdly, I'll look into that before closing
