### ISSUE TITLE
[Alphabet Song ?] An Ukrainian player reported that level 1.2 can't be played

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#432]
We received a mail in Ukrainian that, once tranlated, said:
"**How to open a level**

Thanks for the great game. I can't go to level 1-2. I open it, and there is only a dog running and I have no game. What should I do?

Sent from iPad"

Since the mail is written in Ukrainian we imagine he/she is playing a Learn a language edition, but we don't know which language!
Anyway, the first minigame of PS 1.2.1 in all Lean a language editions is the Alphabet Song, that is coherent with having the dog running.
In fact, if the game does not find the Alphabet Song mp3 and akr files the game is displayed like this:
![image](https://user-images.githubusercontent.com/17926293/188070741-f6255f93-8c09-4be2-9deb-488bacc6c9de.png)
 
I tested the Alphabet Song in all Learn a language editions on Android v2.2.1 and everythng is working fine.
I'll test everything also on iPad and we'll try to collect more info from the player...
... but in the meantime we should check if there's anything in the code that could create this problem

**Comment by FrancyCavallari** [comment]
I was able to reproduce the issue on iPad playing Learn English... everything seems ok (with no warnings) on Android and in the Editor. So I include @StefanoCecere in this issue because I suspect it's someway related the iOS build

**Comment by FrancyCavallari** [comment]
It also happens in Learn German on iPad... and in Learn German iOS no dialog is played all over the game!!!

**Comment by FrancyCavallari** [comment]
Also in Learn Spanish iOS there's no dialog (like in Learn German)... but the Alphabet Song is using the song in English!!!
NOTE: in the original Learn English with Antura app the English Alphabet Song was in Spanish and Italian folders

**Comment by CatmanIta** [comment]
The assets for Alphabet song seem fine, and German has its dialogs. Since everything works in Android & Editor I suspect it may be something with assets not having been rebuilt
