### ISSUE TITLE
[Subtitles] The subtitle panel should block the raycast and the interaction with the scene behind

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#438]
In a few games you can notice that skipping the subtitle is also interacting with the game element itself:
- in Balloons you can pop a balloon of the tutorial round
- in Color Tickle you can pain outside of the letter shape

Better if we modify the subtitles panel to block any raycast and assure that you can't interact with anything else anywhere simply by skipping the subtitle itslef.

**Comment by CatmanIta** [comment]
It already blocks raycasts, but there are several uses of OnMouseDown throughout the games. However, some are on UI itself, so I cannot just fix them all without causing possible problems. I am fixing only the reported ones, just in case, by making them skip the action if the mouse / finger is over a UI element.
