### ISSUE TITLE
[ColorTickle] Multi-character LetterData in ColorTickle color both letters at once

### ISSUE THREAD

**Issue by CatmanIta** [vgwb/Antura#440]

**Comment by CatmanIta** [comment]
Ok, ho capito come funziona Color Tickle, ma per farlo funzionare con più lettere bisogna farci un po' di lavoro. Al momento estrae le UV di una sola lettera, servirebbe estrarle di tutte lettere (posso farlo), poi distinguere su quale lettera si sta scrivendo e riunire le texture generate in una sola prima di passarle nuovamente a text mesh pro

**Comment by CatmanIta** [comment]
We decided to just filter out all those letters from ColorTickle

**Comment by FrancyCavallari** [comment]
We could remove Color Tickle from Learn Hungarian PS 1.13.1 (?)
