### ISSUE TITLE
[Arabic] subtitles should be off by default

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#84]
We may want to re-add an option button to enable them.

**Comment by CatmanIta** [comment]
I disabled them, there is an option to do so in the EditionConfig.
I set the default keeper mode to "Native No Subtitles".

Note that we already have a "subtitles" button in the options menu, but it is tied to the "SubtitlesEnabled" setting of AppSettingsManager, while the system  that controls whether effectively they appear or not is tied to the "keeper mode" (the new system). 
We may want to standardize that and:
- Have an option to show/hide the 'enable subtitles' button, in the EditionConfig
- Use both the keeper mode and the status of that button to decide whether to show or not subtitles

**Comment by CatmanIta** [comment]
Ok, we have several  "kinds" of "subtitles". 
I did some renaming to make sure we have no conflicts.
I also got rid of good part of the "english/arabic" logic around the application tied to subtitles.

- **Help Subtitles** small translations on some words throughout the game, such as the Book and GamesSelector. 

- **Actual Subtitles** When we show the Keeper widget while we play some audio (the text in this case matches the audio). These are handled by the KeeperMode but also by an option in AppSettings.


What I did:
- I moved the **Help Subtitles** to the EditionConfig, so we can control whether they appear per-edition. It is now just called **Help Text**.
- I re-added the user button to enable **Actual Subtitles**. The presence of the button is configurable in the Edition. However, these can appear *only* when these are required by the text logic, as per the Edition default.

**Comment by CatmanIta** [comment]
For this reason, I also renamed "SubtitlesLanguage" to "HelpLanguage" in the Edition, to avoid confusion. Subtitles are always of the same language that is spoken!

**Comment by CatmanIta** [comment]
To be more flexible, I added a separate **ShowKeeperTranslation** to EditionConfig.
This is the one that shows the help text inside the widget.

**Comment by CatmanIta** [comment]
So, here is what we have:

![image](https://user-images.githubusercontent.com/3244662/98958044-296b6b00-2502-11eb-9b0a-88f926407afb.png)


If you set **ShowKeeperTranslation** to true, when subtitles are shown we see this.
![image](https://user-images.githubusercontent.com/3244662/98958127-3e47fe80-2502-11eb-86b0-36ba5596bdd3.png)


If you set **ShowHelpText** to true, we can see the text in the book and other parts, like this.
![image](https://user-images.githubusercontent.com/3244662/98958230-5ddf2700-2502-11eb-9a7a-2526e7efa1ab.png)
