### ISSUE TITLE
[Arabic] Wrong avatar icon when updating from Gplay version

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#91]
On Android, I had the GPlay version installed with the Demo Profile created.
I installed the latest Cloud Build over it and the Demo Profile avatar is not displayed correctly... even if everything else workd fine!
![image](https://user-images.githubusercontent.com/17926293/100996073-eb89c180-3558-11eb-9575-7c5756bf7f81.png)

**Comment by wassimbassil** [comment]
Seems like it works fine on android
