### ISSUE TITLE
[Arabic] Maze game gets stuck after the tutorial round

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#92]
![image](https://user-images.githubusercontent.com/17926293/100996917-f4c75e00-3559-11eb-851f-0169769e9f4a.png)

**Comment by CatmanIta** [comment]
I see that your game was not finding the tah__lettername audio file. Maybe that letter was not present in the arabic folder?
The game breaks if it cannot find that audio file, I fixed that by making it continue regardless of the audio.

**Comment by FrancyCavallari** [comment]
Yes, "Letters" audio folder was missing in Arabic... now it's fixed.
