### ISSUE TITLE
[Arabic] Error in Help dialog about Gender Selection

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#94]
Loc IDs are missing
![image](https://user-images.githubusercontent.com/17926293/101160330-23633880-362f-11eb-8774-ba91d4597d17.png)

**Comment by FrancyCavallari** [comment]
We must decide if we want to keep it or not (Apple?)... and in case translate the texts to Arabic.

**Comment by FrancyCavallari** [comment]
Let's keep it... so we have to fix it!
The debug log says:
`Cannot find id 'UI_Btn_Skip' in table LocalizationTable`

**Comment by FrancyCavallari** [comment]
Better we keep it in 2 languages (like the Parental Gate): Arabic and English

**Comment by CatmanIta** [comment]
Updated so the leftmost texts use Help text, while the rightmost use Native.
I also added the UI key when the ERROR text appears so you can better see where things are missing
