### ISSUE TITLE
[Arabic] Map_Intro_LB_xxx dialogs should not be played

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#96]
The LB-related dialogs to play are set in the PlaysessionDB, correct?

**Comment by CatmanIta** [comment]
We have two LB-related points in which we play audio:

- During the tutorial, Map_Intro and Map_Intro_LB_Alphabet are played. **I removed the Alphabet one as requested.**
- When we reach specifric play sessions in the map, the LB titles, which are found in the LearningBlockDB, are played if found. This uses the AudioFile key found in the LearningBlockDatabase table.

**Comment by FrancyCavallari** [comment]
Wouldn't be better to have only Map_Intro as part of the tutorial and then have the system check if there is any AudioFile set in the LearningBlockDatabase table at 1.1 (like it's set for LearnFrench)?
![image](https://user-images.githubusercontent.com/17926293/104632633-4b1dd580-569e-11eb-9e4d-e4eb3b0c0177.png)

**Comment by FrancyCavallari** [comment]
I also have to update the Arabic PlaySessionDB to include all AudioFiles we want to be played (in the original version they were hardcoded).

**Comment by FrancyCavallari** [comment]
I have updated the PlaySessionDB and generated the JSON... but it gives an error when importing it.
Waiting for @StefanoCecere to check it...
