### ISSUE TITLE
[Arabic] Neither original audio files (Arabic_ea4s) nor new ones (arabic) cover all the game dialogs 

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#97]
Should we mix by hand the audio files in order to have all the dialogs covered?
Or better use a fallback folder (in case a file is not found in Arabic_ea4s then the game automatically check the Arabic folder? 
If we decide for the latter then:
- the App size will increase havily because we have to include 2 full folders
- we should ba able to set the main folder and the fallback one in the Edition config (or in the Lang config)

**Comment by CatmanIta** [comment]
We can actually avoid the size increase if we always treat dialogs that can be different as "variations". There would be no default for fallback, just a main folder with all "shared" dialogs, and 'variations' folders with dialogs that can be different. Then, we can ship the version with its variation only.

This would however mean duplication if many versions want to use the same variation, but I think that would be rare, wouldn't it?

**Comment by CatmanIta** [comment]
We decided we'll have a legacy folder just for the old arabic files.
We'll treat it as an additional language.

**Comment by CatmanIta** [comment]
Created the new Arabic_Legacy language. I set the repository to be setup for the Arabic edition for now.

**Comment by FrancyCavallari** [comment]
Arabic_legacy resources are in place and seems to be working fine... now we need an Arabic-speaker to test and validate them
